name: myapp
description: "本も家計もバッチリよ！"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  googleapis: ^13.2.0
  googleapis_auth: ^1.4.1
  cloud_firestore: ^5.2.1
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_core_web: ^2.17.4
  cloud_firestore_web: ^4.1.1
  url_launcher: ^6.3.0
  shared_preferences: ^2.3.2
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animal_happa_tanuki.png
    - assets/yumekawa_animal_unicorn.png
