// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwXlRXP6ojFbLxQxLkoi_YBQ5SB28neA0',
    appId: '1:613706397793:web:f44ffe831128075dd35220',
    messagingSenderId: '613706397793',
    projectId: 'haruehon-c8837',
    authDomain: 'haruehon-c8837.firebaseapp.com',
    storageBucket: 'haruehon-c8837.appspot.com',
    measurementId: 'G-9W4C1B98XV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3pRb0jR-67DfIwM_obAlhPSGt7vjGHuE',
    appId: '1:613706397793:android:d9e04ef04366b153d35220',
    messagingSenderId: '613706397793',
    projectId: 'haruehon-c8837',
    storageBucket: 'haruehon-c8837.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3UATKOv9LXhLB6W5zXtGdEIRV5gZEHno',
    appId: '1:613706397793:ios:55943bcf12d2ec24d35220',
    messagingSenderId: '613706397793',
    projectId: 'haruehon-c8837',
    storageBucket: 'haruehon-c8837.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3UATKOv9LXhLB6W5zXtGdEIRV5gZEHno',
    appId: '1:613706397793:ios:55943bcf12d2ec24d35220',
    messagingSenderId: '613706397793',
    projectId: 'haruehon-c8837',
    storageBucket: 'haruehon-c8837.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwXlRXP6ojFbLxQxLkoi_YBQ5SB28neA0',
    appId: '1:613706397793:web:b84ee7c1bc964776d35220',
    messagingSenderId: '613706397793',
    projectId: 'haruehon-c8837',
    authDomain: 'haruehon-c8837.firebaseapp.com',
    storageBucket: 'haruehon-c8837.appspot.com',
    measurementId: 'G-D2ZBD1T2YQ',
  );
}
